### ISSUE TITLE
如何启动游戏

### ISSUE THREAD

**Issue by asd5772525** [xiaoqidaov2/game#1]
大佬  install之后如何开始游戏呢。。。
输入注册后直接调用了api  输入开机后提示还没有注册 能否区别一下口令，不直接调用api
或者是我得操作有问题。。。

**Comment by xiaoqidaov2** [comment]
很抱歉之前设置的管理员忘记删除了，并且我也没有将配置文件独立出来，等下更新一个版本。解决此问题

**Comment by xiaoqidaov2** [comment]
已修复，请重新安装或更新插件，目前已经解决逻辑问题，并在启动插件后会初始化一个配置文件config.json，可在配置文件添加管理员名称

**Comment by asd5772525** [comment]
感谢感谢
