### ISSUE TITLE
希望能够增加更详细的接入教程

### ISSUE THREAD

**Issue by Sakura7301** [xiaoqidaov2/game#3]
我在安装了插件之后没有任何反应，config.json中的admins完全不知道该如何配置。
![image](https://github.com/user-attachments/assets/614e2d2f-5d83-4560-8b41-bb11a4427fa2)
此外，希望作者可以支持指令，用于开始或暂停此功能(貌似godcmd直接禁用也可以？)

**Comment by workholmes** [comment]
你直接开机关机不就行了
